## NumPy ' ı Tanıyalım


### NumPy Nedir?

NumPy, dizilerle çalışmak için kullanılan bir Python kütüphanesidir.Ayrıca doğrusal cebir, fourier dönüşümü ve matrisler alanında çalışmaya yönelik fonksiyonları da vardır.NumPy, 2005 yılında Travis Oliphant tarafından yaratıldı. Açık kaynaklı bir projedir ve özgürce kullanabilirsiniz.

### Neden Numpy .. ?

Python'da dizi işlevi gören listeler var, ancak bunların işlenmesi yavaştır.NumPy, geleneksel Python listelerinden 50 kata kadar daha hızlı bir dizi nesnesi sağlamayı amaçlamaktadır.

### NumPy Listelerden Neden Daha Hızlıdır? 
NumPy dizileri, listelerin aksine bellekte tek bir sürekli yerde saklanır, böylece işlemler bunlara çok verimli bir şekilde erişebilir ve bunları işleyebilir.Bu işleve bilgisayar biliminde referans yerelliği denir. NumPy'nin listelerden daha hızlı olmasının temel nedeni budur. Ayrıca en son CPU mimarileriyle çalışmak üzere optimize edilmiştir.

### NumPy Kurulumu

Bir sistemde Python veya PIP yüklü ise ;

"C:\Users\user> pip install numpy"

komutu ile numpy kütüphanesini yükleyebilirsiniz.

In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# Bu işlemden sonra "numpy" kütüphanesini kullanabiliriz.
import numpy 

print("Numpy Kullanılır Durumda...")

Numpy Kullanılır Durumda...


In [3]:
# ÖRNEK 1 : 

import numpy

arr = numpy.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [5]:
# ÖRNEK 2 :
import numpy as np # np kısaltması ile kullanımı

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [6]:
# ÖRNEK 3 : NUMOY SÜRÜMÜNÜ KONTROL ETME
import numpy as np

print(np.__version__)

1.26.4


In [1]:
import numpy as np
5*np.array([1, 2, 3, 4, 5])

array([ 5, 10, 15, 20, 25])