## NumPy Dizileri Oluşturma

In [2]:
# ÖRNEK 1 : Bir NumPy ndarray nesnesi oluşturalım.

import numpy as np

arr = np.array([1, 2, 3, 4, 5]) # 1 boyutlu bir ndarray nesnesi oluşturduk.

print(arr)

print(type(arr)) # type() fonksiyonu ile arr nesnesinin veri tipini öğreniyoruz.

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# NOT :Bir oluşturmak için ndarray,metoda bir liste,tuple veya herhangi bir dizi benzeri nesne geçirebiliriz.

# ÖRNEK 2 : Bir NumPy dizisi oluşturmak için bir tuple kullanalım.

import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


#### 0-D Dizileri
0-D diziler veya Skalerler, bir dizideki elemanlardır. Bir dizideki her değer bir 0-D dizisidir.

In [4]:
# ÖRNEK 3 : 42 değerine sahip 0 boyutlu bir dizi oluşturun

import numpy as np

arr = np.array(42)

print(arr)

42


#### 1-D Diziler
Elemanları 0 boyutlu dizilerden oluşan dizilere tek boyutlu veya 1 boyutlu dizi denir.

In [5]:
# ÖRNEK 4 : 1,2,3,4,5 değerlerini içeren 1 boyutlu bir dizi oluşturalım.

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


#### 2-D Diziler
Elemanları 1 boyutlu dizilerden oluşan dizilere 2 boyutlu dizi denir.Bunlar genellikle matris veya 2. dereceden tensörleri temsil etmek için kullanılır.

In [8]:
# ÖRNEK 5 : 1,2,3 ve 4,5,6 değerlerine sahip iki dizi içeren 2 boyutlu bir dizi oluşturalım.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


#### 3-D Diziler
Elemanları 2 boyutlu diziler (matrisler) olan dizilere 3 boyutlu dizi denir.Bunlar genellikle 3. dereceden bir tensörü temsil etmek için kullanılır.

In [7]:
# ÖRNEK 6 : Her ikisi de 1,2,3 ve 4,5,6 değerlerine sahip iki dizi içeren iki 2 boyutlu diziden oluşan 3 boyutlu bir dizi oluşturalım.

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [9]:
# BOYUT SAYISINI KONTROL EDELİM.

# ÖRNEK 7 : Bir NumPy dizisinin boyut sayısını kontrol edelim.
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim) # ndim özelliği ile dizinin boyut sayısını öğreniyoruz.
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [10]:
# YÜKSEK BOYUTLU DİZİLER : 5 boyutlu bir dizi oluşturalım ve 5 boyuta sahip olduğunu doğrulayalım.

# ÖRNEK 8 : 5 boyutlu bir dizi oluşturalım ve 5 boyuta sahip olduğunu doğrulayalım.

import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


## NumPy Dizi İndeksleme

#### Dizi Elemanlarına Erişim
Dizi indeksleme, bir dizi elemanına erişimle aynıdır.Bir dizi elemanına, onun indeks numarasına başvurarak erişebilirsiniz.NumPy dizilerindeki indeksler 0'dan başlar, yani ilk elemanın indeksi 0, ikinci elemanın indeksi 1'dir.

In [11]:
# ÖRNEK 9 : Dizinin ilk elemanına erişelim.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [12]:
# ÖRNEK 10 : Dizinin ikinci elemanını al.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [13]:
# ÖRNEK 11 : Dizinin üçüncü ve dördüncü elemanlarını topla.

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


#### 2-D Dizilerde Erişim
2 boyutlu dizilerdeki elemanlara erişmek için elemanın boyutunu ve indeksini temsil eden virgülle ayrılmış tam sayıları kullanabiliriz.2 boyutlu dizileri satır ve sütunlardan oluşan bir tablo gibi düşünün; burada boyut satırı, dizin ise sütunu temsil eder.

In [14]:
# ÖRNEK 12 : İlk satır, ikinci sütundaki öğeye erişelim.

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[0, 1])

2


In [15]:
# ÖRNEK 13 : İkinci satır, beşinci sütundaki öğeye erişelim.
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, 4])

10


In [16]:
# ÖRNEK 14 : Birinci dizinin ikinci dizisinin üçüncü öğesine erişelim.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


#### Negatif İndeksleme
Bir diziye sondan erişmek için negatif indekslemeyi kullanın.

In [18]:
# ÖRNEK 15 : 2. boyuttaki son elemanı yazdıralım.

import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr[1, -1])

10


## NumPy Dizi Dilimleme

#### Dizi dilimleme
Python'da dilimleme, elemanları belirli bir indeksten belirli başka bir indekse taşımak anlamına gelir.

[başlangıç : bitiş] --> Diziyi başlangıç ve bitiş indeksleri ile dilimler.

[başlangıç : bitiş : adım] --> Aynı işlemi bu formda ,adım büyüklüğü yazarakta yapabiliriz.


In [20]:
# ÖRNEK 16 : Aşağıdaki dizideki öğeleri dizin 1'den dizin 5'e kadar dilimleyin.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

# NOT : Sonuç başlangıç ​​indeksini içerir ancak bitiş indeksini hariç tutar.

[2 3 4 5]


In [21]:
# ÖRNEK 17 : Öğeleri dizinin 4'üncü elemanında dizinin sonuna kadar dilimleyin.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [22]:
# ÖRNEK 18 : Öğeleri dizinin başlangıcından dizinin 4'üncü elemanına kadar dilimleyin.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


#### Negatif Dilimleme
Bir dizine sondan dilmlemek için eksi operatörünü kullanın.

In [23]:
# ÖRNEK 19 : Dizin 3'ten sondan dizin 1'e doğru dilimleyin:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


#### Adım ile Dilimleme
Dilimleme adımını belirlemek için " step " değeri kullanın.

In [24]:
# ÖRNEK 20 : Diziin ikinici elemanından başlayarak, dizinin sonuna kadar 2'şer 2'şer atlayarak dilimleyin.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1::2])


[2 4 6]


#### 2-D Dizileri Dilimleme

In [25]:
# ÖRNEK 21 : İkinci öğeden, dizin 1'den dizin 4'e kadar öğeleri dilimleyin
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [26]:
# ÖRNEK 22 : Her iki dizinin 2. öğesini yazdırın.

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [27]:
# ÖRNEK 23 : 

import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]
