## NumPy Dizi Shape'i

#### Bir Dizinin Shape'i
Bir dizinin shape'i, her boyuttaki öğe sayısıdır.

#### Bir Dizinin Shape'i Alalım
NumPy dizileri, her indeksin karşılık gelen öğe sayısına sahip olduğu bir demet döndüren, " shape " adı verilen bir özniteliğe sahiptir.

In [1]:
# ÖRNEK 1: 2 boyutlu dizinin shape'ini yazdırın.

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) # (2, 4) ---> 2 satır, 4 sütun

(2, 4)


In [2]:
# ÖRNEK 2:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5) # 5 boyutlu dizi oluşturduk.

print(arr) # [[[[[1 2 3 4]]]]]
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


## NumPy Dizi Reshape'i

#### Bir Dizinin Reshape'i
reshape, bir dizinin şeklini değiştirmek anlamına gelir.Yeniden şekillendirerek boyutları ekleyebilir veya kaldırabilir veya her boyuttaki öğe sayısını değiştirebiliriz.

#### Bir Boyuttan İki Boyuta Döndürmek

In [3]:
# ÖRNEK 3: 12 öğeli 1 boyutlu diziyi 2 boyutlu diziye dönüştürün. En dıştaki boyut, her biri 3 öğeli 4 diziye sahip olacaktır.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Bir Boyuttan Üç Boyuta Döndürmek

In [4]:
# ÖRNEK 4: Aşağıdaki 12 öğeli 1 boyutlu diziyi 3 boyutlu diziye dönüştürün.En dıştaki boyut,her biri 2 öğeli 3 dizi içeren 2 diziye sahip olacaktır.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


#### İstediğiniz Şekilde Yeniden Şekillendirebilir miyiz?
Evet, yeniden şekillendirme için gerekli elemanlar iki şekilde de eşit olduğu sürece yapılabilir.

8 elemanlık bir 1D diziyi 4 elemanlı, 2 sıralı 2D diziye dönüştürebiliriz ancak 3 elemanlı, 3 sıralı 2D diziye dönüştüremez çünkü bu durumda 3x3 = 9 eleman gerekir.

In [5]:
# ÖRNEK 5: 8 öğeli 1 boyutlu diziyi, her boyutta 3 öğeli 2 boyutlu diziye dönüştürmeyi deneyelim.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(3, 3)

print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

#### Bilinmeyen Boyutlar
Bir "bilinmeyen" boyuta sahip olmanıza izin verilir.Bu, yeniden şekillendirme yöntemindeki boyutlardan biri için kesin bir sayı belirtmeniz gerekmediği anlamına gelir.Değer olarak -1'i iletin; NumPy bu sayıyı sizin için hesaplayacaktır.

In [12]:
# ÖRNEK 6 : 8 öğeli 1B diziyi 2x2 öğeli 3B diziye dönüştürün:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2 , -1) # -1, otomatik olarak hesaplanır. 

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### Dizileri Düzleştirme 

Diziyi düzleştirme, çok boyutlu bir diziyi 1 boyutlu bir diziye dönüştürmek anlamına gelir.

In [13]:
# ÖRNEK 7: Convert the array into a 1D array:

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]
