## NumPy - Dizilerde Döngüler

#### Dizilerde Döngüler
Döngü, öğelerin birer birer erişilmesi anlamına gelir.Numpy'de çok boyutlu dizilerle uğraşırken bunu basit bir for döngüsünü kullanarak yapabiliriz.

In [3]:
# ÖRNEK 1 : 1-D dizilerde döngü.

import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [2]:
# ÖRNEK 2 : 2-D dizilerde döngü.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

# NOT : Eğer n boyutlu bir dizi üzerinde döngü yaparsanız, n-1 boyutlu dizi alırsınız.

[1 2 3]
[4 5 6]


In [4]:
# ÖRNEK 3 : 2-D dizilerde her elemanı yazdırma.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [5]:
# ÖRNEK 4 : 3-D dizilerde döngü.
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [6]:
# ÖRNEK 5 : 3-D dizilerde her elemanı yazdırma.

import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z)

1
2
3
4
5
6
7
8
9
10
11
12


#### nditer() Kullanarak Dizilerde Döngüler
nditer() işlevi, çok temelden çok gelişmiş döngülere kadar kullanılabilecek bir yardımcı işlevdir. Döngülerde karşılaştığımız bazı temel sorunları çözebilir.

In [7]:
# ÖRNEK 6 : Dizideki her elemanı yazdırma.

import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


#### Farklı Veri Türlerine Sahip Dizilerde Döngüler
Döngü sırasında öğelerin veri tipini değiştirmek için op_dtypes argümanını kullanabilir ve beklenen veri tipini iletebiliriz.


In [9]:
# ÖRNEK 7 : Dizideki elemanları veri türünü değiştirerek yazdırma.

import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

b'1'
b'2'
b'3'


##### Farklı Adım Boyutları İle Döngüler


In [11]:
# ÖRNEK 8 : 1 öğe atlayan döngü ile 2-D dizinin her bir elemanını yazdırma.

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


#### enumerate() Fonksiyonu ile Döngü Yapmak

In [12]:
# ÖRNEK 9 : 1-D dizilerde enumerate ile döngü yapma.
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [14]:
# ÖRNEK 10 : 2-D dizilerde enumerate ile döngü yapma.

import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
