## Numpy Dizilerini Birleştirme

Birleştirme, iki veya daha fazla dizinin içeriğini tek bir diziye koymak anlamına gelir. NumPy'de dizileri eksenlere göre birleştiriyoruz.concatenate() fonksiyonuna birleştirmek istediğimiz bir dizi diziyi eksenle birlikte iletiyoruz. Eksen belirtilmedi ise 0 olarak alınır.

In [1]:
# ÖRNEK 1 :İki diziyi birleştirme.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [2]:
# ÖRNEK 2 : Satırlar boyunca iki 2 boyutlu diziyi birleştirin (eksen=1).

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


#### Yığın (Stack) İşlevini Kullanarak Dizileri Birleştirme.
Yığın (stack - istifleme) birleştirme ile aynıdır, tek fark yığın yeni bir eksen boyunca yapılır.Birleştirmek istediğimiz dizilerin dizisini eksenle birlikte stack() yöntemine aktarıyoruz. Eksen belirtilmediyse 0 olarak alınır.

In [3]:
# ÖRNEK 3 : Bir boyutlu diziyi birleştirme.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [4]:
# SATIRLAR BOYUNCA YIĞINLAMA : Satırlar boyunca yığınlama için Numpy'ın hstack() fonksiyonunu kullanabilirsiniz.

# ÖRNEK 4 : İki 1 boyutlu diziyi birleştirme.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [5]:
# SÜTUNLAR BOYUNCA YIĞINLAMA : Sütunlar boyunca yığınlama için Numpy'ın vstack() fonksiyonunu kullanabilirsiniz.

# ÖRNEK 5 : İki 1 boyutlu diziyi birleştirme.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [6]:
# DERİNLİK BOYUNCA YIĞINLAMA : Derinlik boyunca yığınlama için Numpy'ın dstack() fonksiyonunu kullanabilirsiniz.

# ÖRNEK 6 : İki 1 boyutlu diziyi birleştirme.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
