## Numpy Diziler Bölme

Bölme, birleştirme işleminin tersidir.Birleştirme, birden çok diziyi tek bir dizide birleştirir ve bölme, bir diziyi birden çok diziye böler.

Dizileri bölmek için " array_split() " kullanıyoruz, bu fonksiyona bölmek istediğimiz diziyi ve bölme sayısını iletiyoruz.

In [2]:
# ÖRNEK 1 : Diziyi 3 parçaya bölelim.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) # Not: Dönüş değeri üç dizi içeren bir listedir.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
# NOT : Dizinin gerekenden daha az öğesi varsa, buna göre uçtan itibaren ayarlanacaktır.

# ÖRNEK 2 : 4 parçaya bölelim.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)


[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [6]:
"""
Ayrıca split() yöntemi de mevcuttur ancak yukarıdaki örnekte olduğu gibi bölme için kaynak dizide öğeler daha az 
olduğunda öğeleri ayarlamaz, array_split() düzgün çalıştı ancak split() başarısız olur.
"""

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.split(arr, 4)

print(newarr)


ValueError: array split does not result in an equal division

#### Dizilere Bölmek

array_split() yönteminin dönüş değeri, bölmelerin her birini bir dizi olarak içeren bir dizidir.Bir diziyi 3 diziye bölerseniz, herhangi bir dizi öğesi gibi bunlara da sonuçtan erişebilirsiniz:


In [7]:
# ÖRNEK 3 : Bölünmüş dizilerde erişim.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


#### 2-D Dizileri Bölme
2 boyutlu dizileri bölerken aynı sözdizimini kullanılır.array_split() yöntemini kullanılır, bölmek istediğiniz diziyi ve bölme sayısını gireriz.

In [10]:
# ÖRNEK 4 : 2D diziyi 3 adet 2-D diziye bölelim.
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

In [11]:
# ÖRNEK 5 : 2D diziyi 3 adet 2-D diziye bölelim.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

newarr

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]

In [13]:
# ÖRNEK 6 : 2-D diziyi satırlar boyunca üç adet 2-D diziye bölelim.

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [14]:
# ÖRENEK 7 : 2-D diziyi satırlar boyunca üç adet 2-D diziye bölmek için hsplit() yöntemini kullanalım.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]