## Numpy Dizilerde Arama

#### Dizilerde Arama

Bir dizide belirli bir değeri arayabilir ve eşleşen dizinleri döndürebilirsiniz.Bir dizide arama yapmak için where() yöntemini kullanabilirsiniz.


In [1]:
# ÖRNEK 1 : Dizdeki 4 elemaının bulunduğu indexleri bulalım.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [2]:
# ÖRNEK 2 : Dizdeki çift sayıların indexlerini bulalım.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [3]:
# ÖRNEK 3 : Dizdeki tek sayıların indexlerini bulalım.
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)


(array([0, 2, 4, 6], dtype=int64),)


#### Sıralı Aramalar 

In [ ]:
# ÖRNEK 4 : Dizdeki 4 elemanının bulunduğu indexleri bulalım.