## Numpy Dizileri Sıralama

#### Dizileri Sıralama
Sıralama, öğeleri düzenli bir sıraya koymak anlamına gelir.Sıralı dizi , sayısal veya alfabetik, artan veya azalan gibi öğelere karşılık gelen bir sıraya sahip olan herhangi bir dizidir. NumPy ndarray nesnesi, belirtilen diziyi sıralayacak olan " sort() " adında bir fonksiyona sahiptir.

In [2]:
# ÖRNEK 1 : Diziyi sıralama
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

# NOT : Bu yöntem, orijinal diziyi değiştirmeden dizinin bir kopyasını döndürür.

[0 1 2 3]


In [3]:
# ÖRNEK 2 : Diziyi alfabetik olarak sıralama

import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [5]:
# ÖRNEK 3 : Boolean dizileri sıralama

import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


#### 2-D Bir Diziyi Sıralama
2-D bir dizide sort() metodunu kullanırsanız, her iki dizi de sıralanacaktır.

In [6]:
# ÖRNEK 4 : 2-D Diziyi Sıralama
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
