## Numpy Random (Rastgele) Sayılar

#### Rastgele Sayılar 
Rastgele sayı her seferinde farklı bir sayı anlamına GELMEZ. Rastgele mantıksal olarak tahmin edilemeyen bir şey anlamına gelir.

### Sahte Rastgele ve Gerçek Rastgele
Bilgisayarlar programlar üzerinde çalışır ve programlar kesin talimatlar kümesidir. Bu da rastgele bir sayı üretmek için bir algoritmanın da olması gerektiği anlamına gelir.

Eğer rastgele sayı üreten bir program varsa bu sayı tahmin edilebilir, dolayısıyla gerçek anlamda rastgele değildir.

Bir üretim algoritması ile üretilen rastgele sayılara yalancı rastgele denir .

Gerçekten rastgele sayılar üretebilir miyiz?

Evet. Bilgisayarlarımızda gerçekten rastgele bir sayı üretmek için rastgele verileri bazı dış kaynaklardan almamız gerekir. Bu dış kaynak genellikle tuş vuruşlarımız, fare hareketlerimiz, ağdaki veriler vb.'dir.

Güvenlikle ilgili olmadığı (örneğin şifreleme anahtarları) veya uygulama temeli rastgelelik olmadığı (örneğin Dijital rulet çarkları) sürece gerçekten rastgele sayılara ihtiyacımız yoktur.

Bu derste sözde rastgele sayılar kullanacağız.

In [1]:
# RASTGELE SAYI ÜRETME

# ÖRNEK 1 : 0 ile 100 arasında rastgele bir tam sayı üretmek.

from numpy import random

x = random.randint(100) # 0 ile 100 arasında rastgele bir " tam sayı " üretir.

print(x)

54


In [2]:
# ÖRNEK 2 : 0 ile 1 arasında rastgele bir float üretmek.
from numpy import random

x = random.rand()

print(x)

0.8490818401190889


In [3]:
# RASTGELE SAYI DİZİLERİ OLUŞTURMA

# ÖRNEK 3 : 0 ile 100 arasında 5 rastgele tam sayı içeren 1 boyutlu bir dizi oluşturmak.
from numpy import random

x=random.randint(100, size=(5))

print(x)

[48 98 75 74  7]


In [5]:
# ÖRNEK 4 : 0 ile 100 arasında 5 rastgele tam sayı içeren,3 satırdan oluşan 2 boyutlu bir dizi oluşturalım.
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[62 89 15 85 68]
 [95 69 15 57 42]
 [27 34 31  7 67]]


In [6]:
# ÖRNEK 5 : 0 ile 100 arasında float sayılar içeren 1 boyutlu bir dizi oluşturalım.
from numpy import random

x = random.rand(5)

print(x)

[0.59631093 0.7947997  0.91314566 0.31531792 0.17796023]


In [7]:
# ÖRNEK 6 : Her satırı 5 rastgele ondalıklı sayı (float) içeren 3 satırlı 2 boyutlu bir dizi oluşturalım.

from numpy import random

x = random.rand(3, 5)

print(x)

[[0.2450057  0.54754688 0.36076424 0.83850315 0.80975053]
 [0.0886377  0.44365196 0.86961562 0.5326727  0.54752061]
 [0.10839655 0.63726587 0.74815192 0.14555166 0.22760822]]


#### Diziden Rastgele Sayı Oluşturma
choice() yöntemi, bir dizisinden rastgele bir değer oluşturmanıza olanak tanır. Parametre olarak bir diziyi alır ve değerlerden birini rastgele döndürür.

In [8]:
# ÖRNEK 7 : Bir dizideki değerlerden birini döndürür.

from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

9


In [14]:
# ÖRNEK 8 : Bir diziden rastele değerlerle 2 boyutlu bir dizi oluşturalım.
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[5 5 3 9 5]
 [9 7 9 9 9]
 [9 9 9 5 5]]


#### Rastgele Veri Dağıtımı


In [2]:
"""
VERİ DAĞITIMI : Tüm olası değerlerin ve her değerin ne sıklıkla meydana geldiğinin bir listesidir.
                İstatistik ve veri bilimi ile çalışırken bu tür listeler önemlidir.
                Random modülü, rastgele oluşturulmuş veri dağılımlarını döndüren yöntemler sunar.
"""

'\nVERİ DAĞITIMI : Tüm olası değerlerin ve her değerin ne sıklıkla meydana geldiğinin bir listesidir.\n                İstatistik ve veri bilimi ile çalışırken bu tür listeler önemlidir.\n                Random modülü, rastgele oluşturulmuş veri dağılımlarını döndüren yöntemler sunar.\n'

In [6]:
# RASTGELE DAĞILIM : Rastgele dağılım, belirli bir olasılık yoğunluk fonksiyonunu izleyen rastgele sayılar kümesidir .

# ÖRNEK 9 
"""
Her değerin 3, 5, 7 veya 9 olması gereken, 100 değer içeren 1 boyutlu bir dizi oluşturun.
Değerin 3 olma olasılığı 0,1 olarak ayarlayın.
Değerin 5 olma olasılığı 0,3 olarak ayarlayın.
Değerin 7 olma olasılığı 0,6 olarak ayarlayın.
Değerin 9 olma olasılığı 0 olarak ayarlayın.
"""

from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(100)) # Tüm olasılık sayılarının toplamı 1 olmalıdır.
print(x)


[7 7 7 7 5 7 5 5 7 7 5 7 3 3 7 7 5 7 7 7 7 3 5 5 5 7 7 7 5 5 7 5 7 7 7 5 3
 7 7 3 5 7 7 5 7 5 5 7 7 7 7 3 5 5 5 7 7 7 3 7 7 7 5 5 7 5 7 5 7 5 7 5 7 7
 7 7 7 5 7 3 3 5 7 5 5 3 5 7 7 7 7 7 3 5 5 7 7 5 7 7]


In [7]:
# ÖRNEK 10 : Yukarıdaki örnekle aynı, ancak her biri 5 değer içeren 3 satırdan oluşan 2 boyutlu bir dizi döndürüyor.

from numpy import random
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.6, 0.0], size=(3, 5))
print(x)

[[3 5 5 5 5]
 [7 7 7 7 7]
 [5 7 5 7 7]]
